# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
# include: package:pedantic/analysis_options.yaml

# Enable linter rules corresponding to the guidelines in Effective Dart
# https://dart.dev/guides/language/effective-dart
include: package:effective_dart/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
# linter:
#   rules:
#     - camel_case_types

analyzer:
#   exclude:
#     - path/to/excluded/files/**
